version: '3.5'

services:
  # For routing external http / https requests
  traefik:
    image: traefik:v2.7
    ports:
      - 80:80
      - 443:443
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.admin-auth.basicauth.users=admin:$$apr1$$RtbxBBZK$z.km/smWZ6z/YRxT9ByJj/
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`admin.rbr.kis.im`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`admin.rbr.kis.im`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=ov@fevlake.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    networks:
      - internal

  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
      # Set in gitlab ci variables
      POSTGRES_PASSWORD:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  traefik-public-certificates:
  postgres-data:

networks:
  internal:
    name: internal
