version: '3.5'

services:
  app: 
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    configs:
      - source: nginx_app
        target: /etc/nginx/conf.d/app.conf
    networks:
      - internal
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend-nginx-http.rule=Host(`rbr.kis.im`)"
        - "traefik.http.routers.backend-nginx-http.entrypoints=http"
        - "traefik.http.routers.backend-nginx-http.middlewares=https-redirect"
        - "traefik.http.routers.backend-nginx-https.rule=Host(`rbr.kis.im`)"
        - "traefik.http.routers.backend-nginx-https.entrypoints=https"
        - "traefik.http.routers.backend-nginx-https.tls=true"
        - "traefik.http.routers.backend-nginx-https.tls.certresolver=le"
        - "traefik.http.routers.backend-nginx-https.service=backend-nginx-svc"
        - "traefik.http.services.backend-nginx-svc.loadbalancer.server.port=8090"

configs:
  nginx_app:
    file: ./.ci/nginx_app.conf

networks:
  internal:
    external: true
